### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by mattstratton** [devopsdays/devopsdays-theme#49]
This is a meta-issue where we can track all the operational items needed prior to go-live with the new theme.

_Items needed in [devopsdays-web](https://github.com/devopsdays/devopsdays-web) should be created as a separate branch and pull request on that repo._

To do some time before go-time:

- [x] [Update `make_new_event.sh` with new parameters](https://github.com/devopsdays/devopsdays-web/issues/1495)
- [x] [Update `sample-event` with the proper starting files](https://github.com/devopsdays/devopsdays-web/issues/1496)
- [x] [Update the files in `examples/speakers` with any new fields](https://github.com/devopsdays/devopsdays-web/issues/1497)
- [x] [Update `yyyy-city.yml` with any new fields, and remove any that are no longer needed](https://github.com/devopsdays/devopsdays-web/issues/1498)
- [x] [Update any "future" events with logos, etc](https://github.com/devopsdays/devopsdays-web/issues/1499)
- [x] [Add `make_new_program.sh` to generate program page and YAML](https://github.com/devopsdays/devopsdays-web/issues/1665)
- [x] Ensure that path separator still works on Windows with the new theme: https://github.com/devopsdays/devopsdays-theme/issues/22
- [x] Fix event nav for small viewscreens: https://github.com/devopsdays/devopsdays-theme/issues/185
- [x] Fix image resizing in gulp: https://github.com/devopsdays/devopsdays-theme/issues/252 which covers https://github.com/devopsdays/devopsdays-theme/issues/134 & https://github.com/devopsdays/devopsdays-theme/issues/153 & https://github.com/devopsdays/devopsdays-theme/issues/266
- [x] Add styling for event sub-pages: https://github.com/devopsdays/devopsdays-theme/issues/243
- [x] Value of event_logo_square needs to be coded to a specific filename: https://github.com/devopsdays/devopsdays-theme/issues/255
- [x] Footer fixes: https://github.com/devopsdays/devopsdays-theme/issues/263, https://github.com/devopsdays/devopsdays-theme/issues/141, https://github.com/devopsdays/devopsdays-theme/issues/218
- [x] Style CTA buttons: https://github.com/devopsdays/devopsdays-theme/issues/167
- [x] Remove event_logo_square key from data files: https://github.com/devopsdays/devopsdays-web/issues/1801
- [x] config.toml updates: https://github.com/devopsdays/devopsdays-web/issues/1780 
- [x] Update event data files on devopsdays-web with small screen icons: https://github.com/devopsdays/devopsdays-web/issues/1819
- [x] Create RSS feed for events and CFP - https://github.com/devopsdays/devopsdays-theme/issues/15

To do immediately before go-time:

- [x] [Regression check](https://github.com/devopsdays/devopsdays-theme/issues/55)

To do at go-time:

- [x] Move speaking page to subdirectory - https://github.com/devopsdays/devopsdays-web/issues/1847
- [x] Change page type of speaking and events pages - https://github.com/devopsdays/devopsdays-web/issues/1947

To do after cutover:

- [x] Update build tasks: https://github.com/devopsdays/devopsdays-web/issues/1791
- [x] Replace https://github.com/devopsdays/devopsdays-web/tree/master/utilities with https://github.com/devopsdays/devopsdays-theme/tree/master/exampleSite/utilities 
- [x] Data cleanup for [event_twitter](https://github.com/devopsdays/devopsdays-theme/issues/214)
- [x] [Remove unneeded and redundant "welcome" event-level nav](https://github.com/devopsdays/devopsdays-web/issues/1829)

**Comment by bridgetkromhout** [comment]
I've got a PR in flight that covers a number of these: https://github.com/devopsdays/devopsdays-theme/pull/248

**Comment by mattstratton** [comment]
I do believe it's possible for me to install the new theme in advance in the `devopsdays-web` repo, but we will not point to it.

I can create a `test.devopsdays.org` URL with Netlify which will build using that theme, so if anyone makes any changes it should update both URLs and we can regression test that way.

**Comment by mattstratton** [comment]
OK, so I have updated the latest version in there, and it's backwards-compatible; so any builds to master on `devopsdays-web` will be visible in the new theme at https://test.devopsdays.org.

Internal links go back to www though, so that's not great.

**Comment by bridgetkromhout** [comment]
The only thing left on this checklist is the regression check; unsure of its status.

**Comment by mattstratton** [comment]
Updated!
